# Generated by Django 4.2.2 on 2023-07-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='grop',
            new_name='group',
        ),
    ]
